// Code generated by mockery v2.45.0. DO NOT EDIT.

package mocks

import (
	ctx "github.com/asymptoter/tonx-take-home-test/pkg/ctx"
	mock "github.com/stretchr/testify/mock"

	repository "github.com/asymptoter/tonx-take-home-test/internal/repository"
)

// CampaignRepository is an autogenerated mock type for the CampaignRepository type
type CampaignRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: c, p
func (_m *CampaignRepository) Create(c ctx.CTX, p repository.CreateCampaignInput) (*repository.Campaign, error) {
	ret := _m.Called(c, p)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *repository.Campaign
	var r1 error
	if rf, ok := ret.Get(0).(func(ctx.CTX, repository.CreateCampaignInput) (*repository.Campaign, error)); ok {
		return rf(c, p)
	}
	if rf, ok := ret.Get(0).(func(ctx.CTX, repository.CreateCampaignInput) *repository.Campaign); ok {
		r0 = rf(c, p)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repository.Campaign)
		}
	}

	if rf, ok := ret.Get(1).(func(ctx.CTX, repository.CreateCampaignInput) error); ok {
		r1 = rf(c, p)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateCouponReservation provides a mock function with given fields: c, p
func (_m *CampaignRepository) CreateCouponReservation(c ctx.CTX, p repository.CreateCouponReservationInput) (*repository.CouponReservation, error) {
	ret := _m.Called(c, p)

	if len(ret) == 0 {
		panic("no return value specified for CreateCouponReservation")
	}

	var r0 *repository.CouponReservation
	var r1 error
	if rf, ok := ret.Get(0).(func(ctx.CTX, repository.CreateCouponReservationInput) (*repository.CouponReservation, error)); ok {
		return rf(c, p)
	}
	if rf, ok := ret.Get(0).(func(ctx.CTX, repository.CreateCouponReservationInput) *repository.CouponReservation); ok {
		r0 = rf(c, p)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repository.CouponReservation)
		}
	}

	if rf, ok := ret.Get(1).(func(ctx.CTX, repository.CreateCouponReservationInput) error); ok {
		r1 = rf(c, p)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetCouponReservation provides a mock function with given fields: c, p
func (_m *CampaignRepository) GetCouponReservation(c ctx.CTX, p repository.GetCouponReservationInput) (*repository.CouponReservation, error) {
	ret := _m.Called(c, p)

	if len(ret) == 0 {
		panic("no return value specified for GetCouponReservation")
	}

	var r0 *repository.CouponReservation
	var r1 error
	if rf, ok := ret.Get(0).(func(ctx.CTX, repository.GetCouponReservationInput) (*repository.CouponReservation, error)); ok {
		return rf(c, p)
	}
	if rf, ok := ret.Get(0).(func(ctx.CTX, repository.GetCouponReservationInput) *repository.CouponReservation); ok {
		r0 = rf(c, p)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repository.CouponReservation)
		}
	}

	if rf, ok := ret.Get(1).(func(ctx.CTX, repository.GetCouponReservationInput) error); ok {
		r1 = rf(c, p)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetLatest provides a mock function with given fields: c, p
func (_m *CampaignRepository) GetLatest(c ctx.CTX, p repository.GetLatestCampaignInput) (*repository.Campaign, error) {
	ret := _m.Called(c, p)

	if len(ret) == 0 {
		panic("no return value specified for GetLatest")
	}

	var r0 *repository.Campaign
	var r1 error
	if rf, ok := ret.Get(0).(func(ctx.CTX, repository.GetLatestCampaignInput) (*repository.Campaign, error)); ok {
		return rf(c, p)
	}
	if rf, ok := ret.Get(0).(func(ctx.CTX, repository.GetLatestCampaignInput) *repository.Campaign); ok {
		r0 = rf(c, p)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repository.Campaign)
		}
	}

	if rf, ok := ret.Get(1).(func(ctx.CTX, repository.GetLatestCampaignInput) error); ok {
		r1 = rf(c, p)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewCampaignRepository creates a new instance of CampaignRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCampaignRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *CampaignRepository {
	mock := &CampaignRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
